// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package main

type UserProto struct {
	Id       string
	Name     string
	Email    string
	Role     string
	Active   bool
	TenantId string
}

func (m *UserProto) GetId() string       { return m.Id }
func (m *UserProto) GetName() string     { return m.Name }
func (m *UserProto) GetEmail() string    { return m.Email }
func (m *UserProto) GetRole() string     { return m.Role }
func (m *UserProto) GetActive() bool     { return m.Active }
func (m *UserProto) GetTenantId() string { return m.TenantId }

func (m *UserProto) ProtoMessage()       {}
func (m *UserProto) Reset()              { *m = UserProto{} }
func (m *UserProto) Size() int           { return 128 }

// A service that handles these messages, calling all the getters to serialize,
// creating a huge cluster of references (fan-out hazard).
func SerializeUserProto(u *UserProto) map[string]interface{} {
	return map[string]interface{}{
		"id":        u.GetId(),
		"name":      u.GetName(),
		"email":     u.GetEmail(),
		"role":      u.GetRole(),
		"active":    u.GetActive(),
		"tenant_id": u.GetTenantId(),
	}
}

func ValidateUserProto(u *UserProto) bool {
	return u.GetId() != "" && u.GetName() != "" && u.GetEmail() != ""
}
